[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build --verbose"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
