[build]
  command = "pnpm install --no-frozen-lockfile && npm run convert"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
