-- New Testament Survey Quiz Questions
-- 50 seminary-quality questions (5 per lesson × 10 lessons)

-- Lesson 1: Introduction to the New Testament Canon and Historical Context
INSERT INTO quiz_questions (lessonId, question, questionType, options, correctAnswer, questionOrder) VALUES
(41, 'According to the biblical and historical evidence discussed in this lesson, which statement best describes the formation of the New Testament canon?', 'multiple_choice', '["The canon was arbitrarily determined by church councils in the 4th century", "The canon emerged through the Spirit-led recognition of apostolic authority and divine inspiration by the early church", "The canon was politically imposed by Constantine", "The canon remains disputed among all Christian traditions today"]', 'The canon emerged through the Spirit-led recognition of apostolic authority and divine inspiration by the early church', 1),

(41, 'Which historical and cultural factor most significantly shaped the context in which the New Testament was written?', 'multiple_choice', '["The Roman Empire''s political structure, Greek language and culture, and Jewish religious heritage", "Exclusively Jewish religious practices with no Gentile influence", "Greek philosophy alone without Jewish or Roman elements", "Medieval European theological frameworks"]', 'The Roman Empire''s political structure, Greek language and culture, and Jewish religious heritage', 2),

(41, 'How does understanding the historical-cultural context of the New Testament enhance biblical interpretation and application?', 'multiple_choice', '["Historical context is irrelevant to spiritual truth", "Context helps us distinguish timeless principles from cultural expressions while maintaining biblical authority", "Context undermines the authority of Scripture", "Context only matters for academic study, not practical ministry"]', 'Context helps us distinguish timeless principles from cultural expressions while maintaining biblical authority', 3),

(41, 'True or False: The New Testament canon was universally recognized immediately after the apostolic age with no development or discussion in the early church.', 'true_false', '["True", "False"]', 'False', 4),

(41, 'In 2-3 sentences, explain how the historical development of the New Testament canon demonstrates both divine sovereignty and human agency in the preservation of Scripture.', 'short_answer', NULL, 'The formation of the New Testament canon involved the Holy Spirit guiding the early church to recognize which writings bore apostolic authority and divine inspiration (2 Peter 1:20-21). While human church leaders engaged in careful discernment and theological reflection, God sovereignly preserved His Word through this process. This demonstrates that biblical inspiration extends not only to the original writing but also to the providential preservation and recognition of canonical Scripture.', 5);

-- Lesson 2: The Synoptic Gospels - Matthew, Mark, and Luke
INSERT INTO quiz_questions (lessonId, question, questionType, options, correctAnswer, questionOrder) VALUES
(42, 'What is the "Synoptic Problem" and why is it theologically significant for understanding the Gospels?', 'multiple_choice', '["The problem of contradictions that undermine Gospel reliability", "The question of how Matthew, Mark, and Luke relate literarily while maintaining their unique theological perspectives", "The difficulty of harmonizing the Gospels with secular history", "The challenge of translating Greek into modern languages"]', 'The question of how Matthew, Mark, and Luke relate literarily while maintaining their unique theological perspectives', 1),

(42, 'Which Gospel is generally considered the earliest and likely served as a source for the other Synoptic Gospels?', 'multiple_choice', '["Matthew, because it appears first in the New Testament", "Mark, based on early church testimony and literary analysis", "Luke, due to its detailed historical prologue", "All three were written simultaneously and independently"]', 'Mark, based on early church testimony and literary analysis', 2),

(42, 'How do the distinct theological emphases of Matthew, Mark, and Luke complement rather than contradict each other?', 'multiple_choice', '["They present contradictory portraits of Jesus that cannot be reconciled", "Each Gospel highlights different aspects of Jesus'' person and work for different audiences while maintaining historical and theological unity", "Only one Gospel is historically accurate; the others are theological fiction", "The differences prove the Gospels are unreliable"]', 'Each Gospel highlights different aspects of Jesus'' person and work for different audiences while maintaining historical and theological unity', 3),

(42, 'True or False: The Synoptic Gospels present Jesus primarily as a moral teacher rather than as the divine Son of God and Messiah.', 'true_false', '["True", "False"]', 'False', 4),

(42, 'In 2-3 sentences, explain how Matthew''s emphasis on Jesus as the fulfillment of Old Testament prophecy serves his theological purpose and audience.', 'short_answer', NULL, 'Matthew wrote primarily to a Jewish-Christian audience, demonstrating that Jesus is the promised Messiah who fulfills the Law and the Prophets (Matthew 5:17). His frequent use of fulfillment formulas ("This was to fulfill what was spoken...") establishes continuity between the Old and New Covenants. This approach bridges Jewish expectations with the reality of Jesus'' person and work, showing that Christianity is the authentic continuation of biblical Judaism.', 5);

-- Lesson 3: The Gospel According to John - The Theological Gospel
INSERT INTO quiz_questions (lessonId, question, questionType, options, correctAnswer, questionOrder) VALUES
(43, 'How does John''s Gospel differ from the Synoptic Gospels in its presentation of Jesus Christ?', 'multiple_choice', '["John contradicts the Synoptics and presents a different Jesus", "John emphasizes Jesus'' divine nature and theological significance more explicitly while complementing the Synoptic portrait", "John is purely theological fiction with no historical value", "John focuses only on Jesus'' humanity, unlike the Synoptics"]', 'John emphasizes Jesus'' divine nature and theological significance more explicitly while complementing the Synoptic portrait', 1),

(43, 'What is the theological significance of the "I AM" statements in John''s Gospel?', 'multiple_choice', '["They are simple self-descriptions with no deeper meaning", "They echo God''s self-revelation to Moses (Exodus 3:14) and assert Jesus'' divine identity", "They prove Jesus was merely a prophet", "They are later additions not original to John''s Gospel"]', 'They echo God''s self-revelation to Moses (Exodus 3:14) and assert Jesus'' divine identity', 2),

(43, 'According to John 20:30-31, what is the stated purpose of John''s Gospel?', 'multiple_choice', '["To provide a complete biography of Jesus'' life", "That readers might believe Jesus is the Christ, the Son of God, and have life in His name", "To correct errors in the Synoptic Gospels", "To establish church doctrine and practice"]', 'That readers might believe Jesus is the Christ, the Son of God, and have life in His name', 3),

(43, 'True or False: The prologue of John''s Gospel (John 1:1-18) establishes Jesus'' pre-existence, deity, and incarnation as foundational to understanding His identity and mission.', 'true_false', '["True", "False"]', 'True', 4),

(43, 'In 2-3 sentences, explain how John''s use of "signs" (σημεῖα) functions to reveal Jesus'' glory and identity.', 'short_answer', NULL, 'John selects seven specific miraculous signs that reveal Jesus'' divine power and messianic identity, pointing beyond the physical miracle to spiritual truth (John 2:11). Each sign demonstrates an aspect of Jesus'' glory and invites faith, serving both evidential and symbolic purposes. The signs culminate in Jesus'' resurrection, the ultimate sign validating His claims and mission (John 20:30-31).', 5);

-- Lesson 4: The Acts of the Apostles - The Church''s Mission
INSERT INTO quiz_questions (lessonId, question, questionType, options, correctAnswer, questionOrder) VALUES
(44, 'What is the central theme of the Book of Acts as revealed in Acts 1:8?', 'multiple_choice', '["The establishment of church government structures", "The Spirit-empowered witness of the church from Jerusalem to the ends of the earth", "The persecution and suffering of early Christians", "The theological debates within the early church"]', 'The Spirit-empowered witness of the church from Jerusalem to the ends of the earth', 1),

(44, 'How does Luke present the relationship between the Holy Spirit and the mission of the church in Acts?', 'multiple_choice', '["The Holy Spirit is mentioned occasionally but plays a minor role", "The Holy Spirit empowers, guides, and directs every aspect of the church''s witness and expansion", "The Holy Spirit only worked through the apostles, not ordinary believers", "The Holy Spirit''s work ended with the apostolic age"]', 'The Holy Spirit empowers, guides, and directs every aspect of the church''s witness and expansion', 2),

(44, 'What theological and practical significance does the Jerusalem Council (Acts 15) have for understanding the relationship between Jewish and Gentile believers?', 'multiple_choice', '["It proves Christianity completely rejected its Jewish roots", "It demonstrates how the early church navigated cultural differences while maintaining theological unity and the gospel''s sufficiency", "It shows that Gentiles must become Jews to be saved", "It has no relevance for contemporary church practice"]', 'It demonstrates how the early church navigated cultural differences while maintaining theological unity and the gospel''s sufficiency', 3),

(44, 'True or False: Acts presents the growth of the church as primarily the result of human strategy and organizational skill rather than divine initiative and power.', 'true_false', '["True", "False"]', 'False', 4),

(44, 'In 2-3 sentences, explain how the pattern of gospel expansion in Acts (Jerusalem → Judea → Samaria → ends of the earth) provides a model for contemporary missions.', 'short_answer', NULL, 'Acts demonstrates that effective mission begins locally and expands concentrically, crossing cultural and geographical boundaries through Spirit-led initiative (Acts 1:8). The pattern shows that the gospel transcends ethnic and cultural barriers while requiring contextual wisdom in presentation. Contemporary missions should likewise combine local rootedness with global vision, cultural sensitivity with theological fidelity, and human planning with dependence on the Holy Spirit''s guidance.', 5);

-- Lesson 5: Pauline Theology - The Apostle to the Gentiles
INSERT INTO quiz_questions (lessonId, question, questionType, options, correctAnswer, questionOrder) VALUES
(45, 'What is the central theme that unifies Paul''s theological teaching across his epistles?', 'multiple_choice', '["Moral improvement through human effort", "Justification by faith in Jesus Christ and union with Him", "Religious ritual and ceremony", "Political liberation from Roman oppression"]', 'Justification by faith in Jesus Christ and union with Him', 1),

(45, 'How does Paul''s doctrine of justification by faith relate to the Old Testament and Jewish theology?', 'multiple_choice', '["It completely rejects Old Testament teaching", "It fulfills and clarifies the Old Testament''s teaching on righteousness through faith, as exemplified in Abraham (Romans 4)", "It creates a new religion unrelated to Judaism", "It contradicts the teachings of Jesus"]', 'It fulfills and clarifies the Old Testament''s teaching on righteousness through faith, as exemplified in Abraham (Romans 4)', 2),

(45, 'What does Paul mean by being "in Christ" (ἐν Χριστῷ), and why is this concept central to his theology?', 'multiple_choice', '["A mystical experience separate from historical faith", "The believer''s spiritual union with Christ through faith, resulting in new identity, righteousness, and transformation", "Mere intellectual agreement with Christian doctrine", "A metaphor with no practical implications"]', 'The believer''s spiritual union with Christ through faith, resulting in new identity, righteousness, and transformation', 3),

(45, 'True or False: Paul teaches that the Law of Moses was evil and had no positive purpose in God''s redemptive plan.', 'true_false', '["True", "False"]', 'False', 4),

(45, 'In 2-3 sentences, explain how Paul''s theology integrates divine sovereignty and human responsibility in salvation.', 'short_answer', NULL, 'Paul affirms God''s sovereign election and predestination (Romans 8:28-30, Ephesians 1:4-5) while simultaneously emphasizing human responsibility to believe and obey the gospel (Romans 10:9-13). This apparent tension reflects the biblical pattern of divine-human cooperation where God''s grace is primary and effective, yet human faith and response are genuine and necessary. Paul holds both truths together without resolving the mystery, calling believers to humble trust in God''s wisdom rather than comprehensive rational explanation.', 5);

-- Lesson 6: Romans - The Gospel of God''s Righteousness
INSERT INTO quiz_questions (lessonId, question, questionType, options, correctAnswer, questionOrder) VALUES
(46, 'What is the central theological argument of Paul''s Epistle to the Romans?', 'multiple_choice', '["The superiority of Jewish religious practices", "The righteousness of God revealed in the gospel, available to all through faith in Jesus Christ", "The political liberation of Christians from Roman rule", "The importance of moral living for salvation"]', 'The righteousness of God revealed in the gospel, available to all through faith in Jesus Christ', 1),

(46, 'How does Romans 1-3 establish the universal need for the gospel?', 'multiple_choice', '["By showing that only Gentiles are sinners", "By demonstrating that all humanity—both Jews and Gentiles—are under sin and accountable to God", "By arguing that sin is not a serious problem", "By teaching that good works can earn salvation"]', 'By demonstrating that all humanity—both Jews and Gentiles—are under sin and accountable to God', 2),

(46, 'What is the theological significance of Romans 8 in Paul''s overall argument?', 'multiple_choice', '["It is a minor digression from the main theme", "It presents the glorious results of justification: no condemnation, Spirit-led life, assurance, and future glorification", "It teaches salvation by works", "It contradicts earlier chapters"]', 'It presents the glorious results of justification: no condemnation, Spirit-led life, assurance, and future glorification', 3),

(46, 'True or False: Romans teaches that God''s righteousness is revealed exclusively through the condemnation of sinners rather than through the justification of believers.', 'true_false', '["True", "False"]', 'False', 4),

(46, 'In 2-3 sentences, explain how Romans 9-11 addresses the question of Israel''s unbelief and God''s faithfulness to His promises.', 'short_answer', NULL, 'Paul demonstrates that Israel''s current unbelief does not nullify God''s faithfulness, as God''s promises were always based on gracious election rather than ethnic descent (Romans 9:6-8). He explains that Israel''s partial hardening has opened the door for Gentile salvation, which will ultimately provoke Israel to jealousy and lead to their future restoration (Romans 11:25-26). This reveals God''s mysterious wisdom in using even human unbelief to accomplish His redemptive purposes for both Jews and Gentiles.', 5);

-- Lesson 7: Corinthian Correspondence - Addressing Church Dysfunction
INSERT INTO quiz_questions (lessonId, question, questionType, options, correctAnswer, questionOrder) VALUES
(47, 'What were the primary issues Paul addressed in his correspondence with the Corinthian church?', 'multiple_choice', '["Political oppression and persecution", "Division, immorality, abuse of spiritual gifts, and doctrinal confusion", "Financial problems only", "Disputes about the Old Testament law"]', 'Division, immorality, abuse of spiritual gifts, and doctrinal confusion', 1),

(47, 'How does Paul''s teaching on the cross and "foolishness of God" (1 Corinthians 1:18-25) address the Corinthians'' worldly wisdom and division?', 'multiple_choice', '["It encourages anti-intellectualism and ignorance", "It shows that God''s wisdom revealed in Christ crucified subverts human pride and provides the only basis for true unity", "It teaches that wisdom is unimportant for Christians", "It promotes division based on spiritual superiority"]', 'It shows that God''s wisdom revealed in Christ crucified subverts human pride and provides the only basis for true unity', 2),

(47, 'What is the theological and practical significance of 1 Corinthians 13 in the context of spiritual gifts?', 'multiple_choice', '["Love is optional for those with powerful spiritual gifts", "Love is the supreme Christian virtue that must govern the exercise of all spiritual gifts", "Spiritual gifts are more important than love", "Love replaces the need for spiritual gifts"]', 'Love is the supreme Christian virtue that must govern the exercise of all spiritual gifts', 3),

(47, 'True or False: Paul teaches that the resurrection of Christ is optional doctrine that doesn''t affect the core of Christian faith.', 'true_false', '["True", "False"]', 'False', 4),

(47, 'In 2-3 sentences, explain how Paul''s teaching on church discipline (1 Corinthians 5) balances grace and holiness.', 'short_answer', NULL, 'Paul commands the removal of an unrepentant immoral member to protect the church''s purity and witness, while the ultimate goal is the person''s restoration and salvation (1 Corinthians 5:5). This demonstrates that genuine love sometimes requires confrontation and boundaries, not tolerance of destructive sin. Church discipline, properly exercised, reflects both God''s holiness and His redemptive purposes, maintaining the tension between grace and truth that characterizes the gospel.', 5);

-- Lesson 8: Prison Epistles - Ephesians, Philippians, Colossians, Philemon
INSERT INTO quiz_questions (lessonId, question, questionType, options, correctAnswer, questionOrder) VALUES
(48, 'What is the central theme of Paul''s Epistle to the Ephesians?', 'multiple_choice', '["Individual salvation only", "God''s eternal purpose to unite all things in Christ and build His church as a display of His wisdom", "Moral improvement through self-effort", "Escape from the material world"]', 'God''s eternal purpose to unite all things in Christ and build His church as a display of His wisdom', 1),

(48, 'How does Philippians demonstrate Paul''s perspective on suffering and joy in Christian ministry?', 'multiple_choice', '["Suffering should be avoided at all costs", "Joy in Christ transcends circumstances, and suffering can advance the gospel and deepen fellowship with Christ", "Christians should never experience joy during suffering", "Suffering indicates God''s displeasure"]', 'Joy in Christ transcends circumstances, and suffering can advance the gospel and deepen fellowship with Christ', 2),

(48, 'What is the primary theological concern Paul addresses in Colossians?', 'multiple_choice', '["Financial stewardship", "The supremacy and sufficiency of Christ against false teaching that diminishes His person and work", "Church government structures", "End times prophecy"]', 'The supremacy and sufficiency of Christ against false teaching that diminishes His person and work', 3),

(48, 'True or False: Paul''s letter to Philemon demonstrates that the gospel transforms social relationships while working within existing structures toward ultimate redemption.', 'true_false', '["True", "False"]', 'True', 4),

(48, 'In 2-3 sentences, explain the theological significance of the Christ hymn in Philippians 2:5-11.', 'short_answer', NULL, 'The Christ hymn presents Jesus'' incarnation, humiliation, and exaltation as the pattern for Christian humility and service, demonstrating that true greatness comes through self-giving love (Philippians 2:5-8). It affirms both Christ''s pre-existent deity and His genuine humanity, showing how He emptied Himself of divine privileges while retaining His divine nature. God''s exaltation of the crucified Christ to universal lordship reveals that the way of the cross is the path to glory, both for Christ and His followers.', 5);

-- Lesson 9: Pastoral Epistles and Hebrews
INSERT INTO quiz_questions (lessonId, question, questionType, options, correctAnswer, questionOrder) VALUES
(49, 'What is the primary purpose of the Pastoral Epistles (1-2 Timothy, Titus)?', 'multiple_choice', '["To provide systematic theology", "To give practical instruction for church leadership, sound doctrine, and ministry organization", "To address persecution from Rome", "To explain end times prophecy"]', 'To give practical instruction for church leadership, sound doctrine, and ministry organization', 1),

(49, 'How does Hebrews present Jesus Christ in relation to the Old Testament sacrificial system?', 'multiple_choice', '["Jesus is one of many acceptable sacrifices", "Jesus is the superior and final high priest who offered the perfect sacrifice once for all", "The Old Testament system is still necessary alongside Christ", "Jesus merely reformed the existing system"]', 'Jesus is the superior and final high priest who offered the perfect sacrifice once for all', 2),

(49, 'What is the theological significance of the "better" theme throughout Hebrews?', 'multiple_choice', '["It denigrates the Old Testament as worthless", "It shows Christ''s superiority to angels, Moses, the priesthood, and the old covenant, fulfilling what they foreshadowed", "It promotes Jewish legalism", "It has no practical application"]', 'It shows Christ''s superiority to angels, Moses, the priesthood, and the old covenant, fulfilling what they foreshadowed', 3),

(49, 'True or False: The Pastoral Epistles emphasize that sound doctrine and godly character are both essential for church leadership.', 'true_false', '["True", "False"]', 'True', 4),

(49, 'In 2-3 sentences, explain how Hebrews 11 defines faith and demonstrates its role in the life of God''s people.', 'short_answer', NULL, 'Hebrews 11:1 defines faith as confidence in what we hope for and assurance about what we cannot see, grounding Christian hope in God''s promises rather than present circumstances. The chapter presents a catalog of Old Testament saints who lived by faith, demonstrating that faith has always been the principle by which God''s people relate to Him and persevere through trials. This "great cloud of witnesses" encourages believers to run with endurance, fixing their eyes on Jesus, the ultimate example and object of faith (Hebrews 12:1-2).', 5);

-- Lesson 10: General Epistles and Revelation
INSERT INTO quiz_questions (lessonId, question, questionType, options, correctAnswer, questionOrder) VALUES
(50, 'What is the central concern of James'' epistle regarding faith and works?', 'multiple_choice', '["Works earn salvation independent of faith", "Genuine faith inevitably produces works as evidence of its reality", "Faith and works are unrelated", "Works are optional for believers"]', 'Genuine faith inevitably produces works as evidence of its reality', 1),

(50, 'How do the epistles of Peter address suffering and persecution in the Christian life?', 'multiple_choice', '["Suffering indicates God''s judgment on sin", "Suffering for righteousness is a means of sanctification and witness, following Christ''s example", "Christians should never suffer", "Suffering should be avoided through compromise"]', 'Suffering for righteousness is a means of sanctification and witness, following Christ''s example', 2),

(50, 'What is the primary message of the Book of Revelation?', 'multiple_choice', '["A detailed timeline of future events", "Jesus Christ is sovereign over history, will judge evil, and will consummate His kingdom in ultimate victory", "Escape from earthly troubles through secret knowledge", "Political commentary on the Roman Empire only"]', 'Jesus Christ is sovereign over history, will judge evil, and will consummate His kingdom in ultimate victory', 3),

(50, 'True or False: The General Epistles (James, 1-2 Peter, 1-3 John, Jude) provide practical instruction for Christian living while addressing specific challenges facing the early church.', 'true_false', '["True", "False"]', 'True', 4),

(50, 'In 2-3 sentences, explain how Revelation''s apocalyptic imagery functions to encourage persecuted believers.', 'short_answer', NULL, 'Revelation uses vivid symbolic imagery drawn from Old Testament prophecy to unveil spiritual realities behind earthly events, showing that Christ reigns despite apparent chaos (Revelation 1:12-18). The visions assure believers that their present suffering is temporary and meaningful within God''s sovereign plan, while their ultimate victory is certain through Christ''s triumph. This perspective enables faithful endurance by revealing that current persecution is part of the cosmic conflict between God''s kingdom and Satan''s rebellion, which will culminate in Christ''s final victory and the new creation (Revelation 21-22).', 5);
