CREATE TABLE `payment_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`paymentPlanId` int,
	`amount` int NOT NULL,
	`paymentNumber` int,
	`paymentDate` timestamp NOT NULL DEFAULT (now()),
	`status` enum('succeeded','failed','refunded','pending') NOT NULL DEFAULT 'pending',
	`stripePaymentIntentId` varchar(255),
	`stripeInvoiceId` varchar(255),
	`failureReason` text,
	`refundedAt` timestamp,
	`refundAmount` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `payment_history_id` PRIMARY KEY(`id`),
	CONSTRAINT `payment_history_stripePaymentIntentId_unique` UNIQUE(`stripePaymentIntentId`)
);
--> statement-breakpoint
CREATE TABLE `payment_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`planType` enum('LEARNING_PATH','BUNDLE_3_COURSE','CHAPLAINCY_TRAINING') NOT NULL,
	`bundleId` int,
	`learningPathId` int,
	`totalAmount` int NOT NULL,
	`monthlyAmount` int NOT NULL,
	`paymentsTotal` int NOT NULL DEFAULT 6,
	`paymentsCompleted` int NOT NULL DEFAULT 0,
	`paymentsRemaining` int NOT NULL DEFAULT 6,
	`nextPaymentDate` timestamp NOT NULL,
	`status` enum('active','paused','completed','cancelled') NOT NULL DEFAULT 'active',
	`stripeSubscriptionId` varchar(255),
	`stripeCustomerId` varchar(255) NOT NULL,
	`agreementAcceptedAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	`cancelledAt` timestamp,
	CONSTRAINT `payment_plans_id` PRIMARY KEY(`id`),
	CONSTRAINT `payment_plans_stripeSubscriptionId_unique` UNIQUE(`stripeSubscriptionId`)
);
