CREATE TABLE `chaplaincy_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`address` text NOT NULL,
	`dateOfBirth` varchar(20) NOT NULL,
	`currentMinistryRole` varchar(255),
	`yearsInMinistry` int NOT NULL,
	`ordainedStatus` enum('ordained','licensed','not_ordained') NOT NULL,
	`denominationAffiliation` varchar(255),
	`ministryExperienceDescription` text NOT NULL,
	`chaplaincy_interest` enum('healthcare','military','correctional','corporate','educational','other') NOT NULL,
	`chaplaincy_interest_other` varchar(255),
	`motivationStatement` text NOT NULL,
	`reference1Name` varchar(255) NOT NULL,
	`reference1Email` varchar(320) NOT NULL,
	`reference1Phone` varchar(50) NOT NULL,
	`reference1Relationship` varchar(255) NOT NULL,
	`reference2Name` varchar(255) NOT NULL,
	`reference2Email` varchar(320) NOT NULL,
	`reference2Phone` varchar(50) NOT NULL,
	`reference2Relationship` varchar(255) NOT NULL,
	`backgroundCheckConsent` boolean NOT NULL,
	`backgroundCheckCompleted` boolean NOT NULL DEFAULT false,
	`backgroundCheckDate` timestamp,
	`backgroundCheckStatus` enum('pending','clear','review_required','failed') DEFAULT 'pending',
	`status` enum('pending','under_review','approved','rejected') NOT NULL DEFAULT 'pending',
	`reviewedBy` int,
	`reviewNotes` text,
	`rejectionReason` text,
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`reviewedAt` timestamp,
	`approvedAt` timestamp,
	CONSTRAINT `chaplaincy_applications_id` PRIMARY KEY(`id`)
);
