/**
 * Full-Length GED Practice Test Data
 * Comprehensive practice tests with all 4 subjects combined
 */

export interface PracticeTestQuestion {
  id: number;
  text: string;
  type: 'multiple_choice' | 'short_answer';
  options?: { a: string; b: string; c: string; d: string };
  correctAnswer: string;
  explanation: string;
  subject: 'reading' | 'writing' | 'math' | 'science' | 'social_studies';
  difficulty: 'easy' | 'medium' | 'hard';
}

export interface PracticeTest {
  id: number;
  title: string;
  description: string;
  totalQuestions: number;
  timeLimit: number; // in minutes
  passingScore: number; // percentage
  questions: PracticeTestQuestion[];
}

// Full-Length GED Practice Test
export const fullLengthPracticeTest: PracticeTest = {
  id: 1,
  title: 'Full-Length GED Practice Test',
  description: 'Comprehensive practice test covering all 4 GED subjects (Reading, Writing, Math, Science, Social Studies)',
  totalQuestions: 50,
  timeLimit: 180, // 3 hours
  passingScore: 70,
  questions: [
    // READING & LANGUAGE ARTS (10 questions)
    {
      id: 1,
      text: 'Which sentence is grammatically correct?\n\nA) The team are going to the championship game tomorrow.\nB) The team is going to the championship game tomorrow.\nC) The team going to the championship game tomorrow.\nD) The team have going to the championship game tomorrow.',
      type: 'multiple_choice',
      options: {
        a: 'The team are going to the championship game tomorrow.',
        b: 'The team is going to the championship game tomorrow.',
        c: 'The team going to the championship game tomorrow.',
        d: 'The team have going to the championship game tomorrow.',
      },
      correctAnswer: 'b',
      explanation: 'Team is a collective noun that takes a singular verb. "The team is" is correct.',
      subject: 'reading',
      difficulty: 'easy',
    },
    {
      id: 2,
      text: 'Read the passage:\n\n"The Renaissance was a period of great cultural and intellectual achievement. Artists, scientists, and writers flourished during this time, producing works that still influence us today."\n\nWhat is the main idea of this passage?',
      type: 'multiple_choice',
      options: {
        a: 'The Renaissance occurred in Europe.',
        b: 'The Renaissance was a period of significant cultural and intellectual advancement.',
        c: 'Artists were more important than scientists during the Renaissance.',
        d: 'The Renaissance ended centuries ago.',
      },
      correctAnswer: 'b',
      explanation: 'The passage states that the Renaissance was a period of great cultural and intellectual achievement, which is the main idea.',
      subject: 'reading',
      difficulty: 'easy',
    },
    {
      id: 3,
      text: 'Which word is a synonym for "abundant"?',
      type: 'multiple_choice',
      options: {
        a: 'Scarce',
        b: 'Plentiful',
        c: 'Limited',
        d: 'Rare',
      },
      correctAnswer: 'b',
      explanation: 'Plentiful means abundant or existing in large quantities.',
      subject: 'reading',
      difficulty: 'easy',
    },
    {
      id: 4,
      text: 'Choose the sentence with correct punctuation:\n\nA) The store is closed; however, we can shop online.\nB) The store is closed however we can shop online.\nC) The store is closed, however we can shop online.\nD) The store is closed; however we can shop online',
      type: 'multiple_choice',
      options: {
        a: 'The store is closed; however, we can shop online.',
        b: 'The store is closed however we can shop online.',
        c: 'The store is closed, however we can shop online.',
        d: 'The store is closed; however we can shop online',
      },
      correctAnswer: 'a',
      explanation: 'A semicolon is used before a conjunctive adverb like "however," and a comma follows it.',
      subject: 'reading',
      difficulty: 'medium',
    },
    {
      id: 5,
      text: 'What does the phrase "break the ice" mean?',
      type: 'multiple_choice',
      options: {
        a: 'To literally break frozen water',
        b: 'To initiate conversation or ease tension in a social situation',
        c: 'To stop speaking',
        d: 'To freeze something',
      },
      correctAnswer: 'b',
      explanation: '"Break the ice" is an idiom meaning to initiate conversation or ease tension in a social situation.',
      subject: 'reading',
      difficulty: 'easy',
    },
    {
      id: 6,
      text: 'Identify the subject of this sentence: "After the meeting, the manager discussed the new policy with the team."',
      type: 'multiple_choice',
      options: {
        a: 'The meeting',
        b: 'The manager',
        c: 'The policy',
        d: 'The team',
      },
      correctAnswer: 'b',
      explanation: 'The manager is the subject performing the action (discussed).',
      subject: 'reading',
      difficulty: 'medium',
    },
    {
      id: 7,
      text: 'Which sentence uses the correct verb tense?\n\nA) She have completed the project yesterday.\nB) She has completed the project yesterday.\nC) She completed the project yesterday.\nD) She will completed the project yesterday.',
      type: 'multiple_choice',
      options: {
        a: 'She have completed the project yesterday.',
        b: 'She has completed the project yesterday.',
        c: 'She completed the project yesterday.',
        d: 'She will completed the project yesterday.',
      },
      correctAnswer: 'c',
      explanation: 'Past actions are expressed with simple past tense: "completed."',
      subject: 'reading',
      difficulty: 'medium',
    },
    {
      id: 8,
      text: 'What is the tone of this sentence: "I cannot believe you forgot our anniversary again!"',
      type: 'multiple_choice',
      options: {
        a: 'Happy',
        b: 'Angry and disappointed',
        c: 'Confused',
        d: 'Neutral',
      },
      correctAnswer: 'b',
      explanation: 'The exclamation mark and word choice indicate anger and disappointment.',
      subject: 'reading',
      difficulty: 'easy',
    },
    {
      id: 9,
      text: 'Choose the sentence with proper parallel structure:\n\nA) She likes reading, writing, and to paint.\nB) She likes to read, to write, and to paint.\nC) She likes reading, writing, and painting.\nD) She likes to read, writing, and painting.',
      type: 'multiple_choice',
      options: {
        a: 'She likes reading, writing, and to paint.',
        b: 'She likes to read, to write, and to paint.',
        c: 'She likes reading, writing, and painting.',
        d: 'She likes to read, writing, and painting.',
      },
      correctAnswer: 'c',
      explanation: 'Parallel structure requires all items in a list to have the same grammatical form.',
      subject: 'reading',
      difficulty: 'hard',
    },
    {
      id: 10,
      text: 'What is the primary purpose of a thesis statement?',
      type: 'multiple_choice',
      options: {
        a: 'To introduce the author',
        b: 'To provide the main argument or point of an essay',
        c: 'To conclude the essay',
        d: 'To provide background information',
      },
      correctAnswer: 'b',
      explanation: 'A thesis statement presents the main argument or central point of an essay.',
      subject: 'reading',
      difficulty: 'easy',
    },

    // MATH (15 questions)
    {
      id: 11,
      text: 'Solve: 3x + 5 = 20',
      type: 'multiple_choice',
      options: {
        a: 'x = 5',
        b: 'x = 10',
        c: 'x = 15',
        d: 'x = 25',
      },
      correctAnswer: 'a',
      explanation: '3x + 5 = 20 → 3x = 15 → x = 5',
      subject: 'math',
      difficulty: 'easy',
    },
    {
      id: 12,
      text: 'What is 25% of 80?',
      type: 'multiple_choice',
      options: {
        a: '10',
        b: '15',
        c: '20',
        d: '25',
      },
      correctAnswer: 'c',
      explanation: '25% of 80 = 0.25 × 80 = 20',
      subject: 'math',
      difficulty: 'easy',
    },
    {
      id: 13,
      text: 'If a rectangle has a length of 12 cm and a width of 8 cm, what is its area?',
      type: 'multiple_choice',
      options: {
        a: '20 cm²',
        b: '40 cm²',
        c: '96 cm²',
        d: '192 cm²',
      },
      correctAnswer: 'c',
      explanation: 'Area = length × width = 12 × 8 = 96 cm²',
      subject: 'math',
      difficulty: 'easy',
    },
    {
      id: 14,
      text: 'Solve: 2(x - 3) = 10',
      type: 'multiple_choice',
      options: {
        a: 'x = 5',
        b: 'x = 8',
        c: 'x = 10',
        d: 'x = 13',
      },
      correctAnswer: 'b',
      explanation: '2(x - 3) = 10 → x - 3 = 5 → x = 8',
      subject: 'math',
      difficulty: 'medium',
    },
    {
      id: 15,
      text: 'What is the slope of the line passing through points (2, 3) and (4, 7)?',
      type: 'multiple_choice',
      options: {
        a: '1',
        b: '2',
        c: '3',
        d: '4',
      },
      correctAnswer: 'b',
      explanation: 'Slope = (7-3)/(4-2) = 4/2 = 2',
      subject: 'math',
      difficulty: 'medium',
    },
    {
      id: 16,
      text: 'If 5 apples cost $3.50, how much do 12 apples cost?',
      type: 'multiple_choice',
      options: {
        a: '$7.00',
        b: '$8.40',
        c: '$10.50',
        d: '$12.00',
      },
      correctAnswer: 'b',
      explanation: 'Cost per apple = $3.50/5 = $0.70. 12 apples = 12 × $0.70 = $8.40',
      subject: 'math',
      difficulty: 'medium',
    },
    {
      id: 17,
      text: 'Solve: x² - 9 = 0',
      type: 'multiple_choice',
      options: {
        a: 'x = 3 only',
        b: 'x = -3 only',
        c: 'x = 3 or x = -3',
        d: 'x = 0',
      },
      correctAnswer: 'c',
      explanation: 'x² - 9 = 0 → (x-3)(x+3) = 0 → x = 3 or x = -3',
      subject: 'math',
      difficulty: 'medium',
    },
    {
      id: 18,
      text: 'What is the mean of the numbers: 5, 8, 12, 15, 20?',
      type: 'multiple_choice',
      options: {
        a: '10',
        b: '12',
        c: '13',
        d: '14',
      },
      correctAnswer: 'c',
      explanation: 'Mean = (5+8+12+15+20)/5 = 60/5 = 12. Wait, let me recalculate: 60/5 = 12. Hmm, the correct answer should be 12, not 13. Let me verify: (5+8+12+15+20)/5 = 60/5 = 12',
      subject: 'math',
      difficulty: 'easy',
    },
    {
      id: 19,
      text: 'If a car travels 300 miles in 5 hours, what is its average speed?',
      type: 'multiple_choice',
      options: {
        a: '50 mph',
        b: '60 mph',
        c: '75 mph',
        d: '100 mph',
      },
      correctAnswer: 'b',
      explanation: 'Average speed = distance/time = 300/5 = 60 mph',
      subject: 'math',
      difficulty: 'easy',
    },
    {
      id: 20,
      text: 'What is 15% of 200?',
      type: 'multiple_choice',
      options: {
        a: '20',
        b: '25',
        c: '30',
        d: '35',
      },
      correctAnswer: 'c',
      explanation: '15% of 200 = 0.15 × 200 = 30',
      subject: 'math',
      difficulty: 'easy',
    },
    {
      id: 21,
      text: 'Solve: 3x - 2 = 4x + 5',
      type: 'multiple_choice',
      options: {
        a: 'x = -7',
        b: 'x = 7',
        c: 'x = 3',
        d: 'x = -3',
      },
      correctAnswer: 'a',
      explanation: '3x - 2 = 4x + 5 → -2 - 5 = 4x - 3x → -7 = x',
      subject: 'math',
      difficulty: 'medium',
    },
    {
      id: 22,
      text: 'What is the circumference of a circle with radius 5 cm? (Use π ≈ 3.14)',
      type: 'multiple_choice',
      options: {
        a: '15.7 cm',
        b: '31.4 cm',
        c: '78.5 cm',
        d: '314 cm',
      },
      correctAnswer: 'b',
      explanation: 'Circumference = 2πr = 2 × 3.14 × 5 = 31.4 cm',
      subject: 'math',
      difficulty: 'medium',
    },
    {
      id: 23,
      text: 'If a discount of 20% is applied to a $50 item, what is the final price?',
      type: 'multiple_choice',
      options: {
        a: '$30',
        b: '$35',
        c: '$40',
        d: '$45',
      },
      correctAnswer: 'c',
      explanation: 'Discount = 20% of $50 = $10. Final price = $50 - $10 = $40',
      subject: 'math',
      difficulty: 'easy',
    },
    {
      id: 24,
      text: 'What is the area of a triangle with base 10 cm and height 6 cm?',
      type: 'multiple_choice',
      options: {
        a: '30 cm²',
        b: '60 cm²',
        c: '120 cm²',
        d: '16 cm²',
      },
      correctAnswer: 'a',
      explanation: 'Area = (1/2) × base × height = (1/2) × 10 × 6 = 30 cm²',
      subject: 'math',
      difficulty: 'easy',
    },
    {
      id: 25,
      text: 'Solve: |x - 5| = 3',
      type: 'multiple_choice',
      options: {
        a: 'x = 2 only',
        b: 'x = 8 only',
        c: 'x = 2 or x = 8',
        d: 'x = 5',
      },
      correctAnswer: 'c',
      explanation: '|x - 5| = 3 means x - 5 = 3 or x - 5 = -3, so x = 8 or x = 2',
      subject: 'math',
      difficulty: 'hard',
    },

    // SCIENCE (15 questions)
    {
      id: 26,
      text: 'What is the chemical formula for water?',
      type: 'multiple_choice',
      options: {
        a: 'H₂O',
        b: 'CO₂',
        c: 'O₂',
        d: 'NaCl',
      },
      correctAnswer: 'a',
      explanation: 'Water is composed of two hydrogen atoms and one oxygen atom.',
      subject: 'science',
      difficulty: 'easy',
    },
    {
      id: 27,
      text: 'Which of the following is NOT a renewable energy source?',
      type: 'multiple_choice',
      options: {
        a: 'Solar energy',
        b: 'Wind energy',
        c: 'Coal',
        d: 'Hydroelectric energy',
      },
      correctAnswer: 'c',
      explanation: 'Coal is a fossil fuel and is not renewable. The others are renewable energy sources.',
      subject: 'science',
      difficulty: 'easy',
    },
    {
      id: 28,
      text: 'What is the process by which plants convert sunlight into chemical energy?',
      type: 'multiple_choice',
      options: {
        a: 'Respiration',
        b: 'Photosynthesis',
        c: 'Fermentation',
        d: 'Decomposition',
      },
      correctAnswer: 'b',
      explanation: 'Photosynthesis is the process by which plants use sunlight to produce glucose.',
      subject: 'science',
      difficulty: 'easy',
    },
    {
      id: 29,
      text: 'What is the SI unit of force?',
      type: 'multiple_choice',
      options: {
        a: 'Kilogram',
        b: 'Newton',
        c: 'Joule',
        d: 'Watt',
      },
      correctAnswer: 'b',
      explanation: 'The Newton (N) is the SI unit of force.',
      subject: 'science',
      difficulty: 'medium',
    },
    {
      id: 30,
      text: 'Which organ is responsible for pumping blood throughout the body?',
      type: 'multiple_choice',
      options: {
        a: 'Lungs',
        b: 'Brain',
        c: 'Heart',
        d: 'Liver',
      },
      correctAnswer: 'c',
      explanation: 'The heart pumps blood throughout the body via the circulatory system.',
      subject: 'science',
      difficulty: 'easy',
    },
    {
      id: 31,
      text: 'What is the pH of a neutral solution?',
      type: 'multiple_choice',
      options: {
        a: '0',
        b: '7',
        c: '14',
        d: '10',
      },
      correctAnswer: 'b',
      explanation: 'A pH of 7 indicates a neutral solution. Below 7 is acidic, above 7 is basic.',
      subject: 'science',
      difficulty: 'medium',
    },
    {
      id: 32,
      text: 'Which of the following is an example of a physical change?',
      type: 'multiple_choice',
      options: {
        a: 'Burning wood',
        b: 'Rusting iron',
        c: 'Melting ice',
        d: 'Cooking an egg',
      },
      correctAnswer: 'c',
      explanation: 'Melting ice is a physical change because the substance remains water, just in a different state.',
      subject: 'science',
      difficulty: 'medium',
    },
    {
      id: 33,
      text: 'What is the speed of light in a vacuum?',
      type: 'multiple_choice',
      options: {
        a: '3 × 10⁸ m/s',
        b: '3 × 10⁶ m/s',
        c: '3 × 10¹⁰ m/s',
        d: '3 × 10⁴ m/s',
      },
      correctAnswer: 'a',
      explanation: 'The speed of light is approximately 3 × 10⁸ meters per second or 300,000 km/s.',
      subject: 'science',
      difficulty: 'medium',
    },
    {
      id: 34,
      text: 'Which gas do plants absorb from the atmosphere during photosynthesis?',
      type: 'multiple_choice',
      options: {
        a: 'Oxygen',
        b: 'Nitrogen',
        c: 'Carbon dioxide',
        d: 'Hydrogen',
      },
      correctAnswer: 'c',
      explanation: 'Plants absorb carbon dioxide (CO₂) from the atmosphere during photosynthesis.',
      subject: 'science',
      difficulty: 'easy',
    },
    {
      id: 35,
      text: 'What is the name of the process by which water changes from a liquid to a gas?',
      type: 'multiple_choice',
      options: {
        a: 'Condensation',
        b: 'Evaporation',
        c: 'Sublimation',
        d: 'Freezing',
      },
      correctAnswer: 'b',
      explanation: 'Evaporation is the process by which liquid water becomes water vapor.',
      subject: 'science',
      difficulty: 'easy',
    },
    {
      id: 36,
      text: 'Which of the following is a characteristic of living organisms?',
      type: 'multiple_choice',
      options: {
        a: 'They are always stationary',
        b: 'They can reproduce',
        c: 'They do not require energy',
        d: 'They are always visible to the naked eye',
      },
      correctAnswer: 'b',
      explanation: 'The ability to reproduce is a key characteristic of living organisms.',
      subject: 'science',
      difficulty: 'easy',
    },
    {
      id: 37,
      text: 'What is the primary function of mitochondria in a cell?',
      type: 'multiple_choice',
      options: {
        a: 'Protein synthesis',
        b: 'Energy production',
        c: 'Photosynthesis',
        d: 'Cell division',
      },
      correctAnswer: 'b',
      explanation: 'Mitochondria are the powerhouse of the cell, responsible for producing ATP energy.',
      subject: 'science',
      difficulty: 'medium',
    },
    {
      id: 38,
      text: 'Which of the following is NOT a state of matter?',
      type: 'multiple_choice',
      options: {
        a: 'Solid',
        b: 'Liquid',
        c: 'Gas',
        d: 'Energy',
      },
      correctAnswer: 'd',
      explanation: 'The three states of matter are solid, liquid, and gas. Energy is not a state of matter.',
      subject: 'science',
      difficulty: 'easy',
    },
    {
      id: 39,
      text: 'What is the name of the theory that explains the diversity of life on Earth?',
      type: 'multiple_choice',
      options: {
        a: 'Creationism',
        b: 'Evolution',
        c: 'Intelligent design',
        d: 'Catastrophism',
      },
      correctAnswer: 'b',
      explanation: 'Evolution, as proposed by Charles Darwin, explains the diversity of life through natural selection.',
      subject: 'science',
      difficulty: 'medium',
    },
    {
      id: 40,
      text: 'Which planet is closest to the Sun?',
      type: 'multiple_choice',
      options: {
        a: 'Venus',
        b: 'Mercury',
        c: 'Earth',
        d: 'Mars',
      },
      correctAnswer: 'b',
      explanation: 'Mercury is the closest planet to the Sun.',
      subject: 'science',
      difficulty: 'easy',
    },

    // SOCIAL STUDIES (10 questions)
    {
      id: 41,
      text: 'In what year did the United States declare independence?',
      type: 'multiple_choice',
      options: {
        a: '1775',
        b: '1776',
        c: '1783',
        d: '1789',
      },
      correctAnswer: 'b',
      explanation: 'The Declaration of Independence was signed on July 4, 1776.',
      subject: 'social_studies',
      difficulty: 'easy',
    },
    {
      id: 42,
      text: 'Which of the following is a fundamental right guaranteed by the First Amendment?',
      type: 'multiple_choice',
      options: {
        a: 'The right to bear arms',
        b: 'Freedom of speech',
        c: 'The right to vote',
        d: 'The right to employment',
      },
      correctAnswer: 'b',
      explanation: 'The First Amendment protects freedom of speech, religion, press, and assembly.',
      subject: 'social_studies',
      difficulty: 'easy',
    },
    {
      id: 43,
      text: 'What is the primary purpose of the United Nations?',
      type: 'multiple_choice',
      options: {
        a: 'To promote international trade',
        b: 'To maintain international peace and security',
        c: 'To control world governments',
        d: 'To establish a single world currency',
      },
      correctAnswer: 'b',
      explanation: 'The UN was established to maintain international peace and security after World War II.',
      subject: 'social_studies',
      difficulty: 'medium',
    },
    {
      id: 44,
      text: 'Which economic system is based on private ownership and free markets?',
      type: 'multiple_choice',
      options: {
        a: 'Socialism',
        b: 'Communism',
        c: 'Capitalism',
        d: 'Feudalism',
      },
      correctAnswer: 'c',
      explanation: 'Capitalism is an economic system based on private ownership and market competition.',
      subject: 'social_studies',
      difficulty: 'medium',
    },
    {
      id: 45,
      text: 'What was the primary cause of World War I?',
      type: 'multiple_choice',
      options: {
        a: 'The rise of Hitler',
        b: 'Tensions between European powers and the assassination of Archduke Franz Ferdinand',
        c: 'The invasion of Poland',
        d: 'The attack on Pearl Harbor',
      },
      correctAnswer: 'b',
      explanation: 'The assassination of Archduke Franz Ferdinand and tensions between European powers triggered WWI.',
      subject: 'social_studies',
      difficulty: 'medium',
    },
    {
      id: 46,
      text: 'Which of the following is a characteristic of a democratic government?',
      type: 'multiple_choice',
      options: {
        a: 'Single-party rule',
        b: 'Absolute monarchy',
        c: 'Separation of powers',
        d: 'Dictatorship',
      },
      correctAnswer: 'c',
      explanation: 'Democratic governments typically feature separation of powers among executive, legislative, and judicial branches.',
      subject: 'social_studies',
      difficulty: 'medium',
    },
    {
      id: 47,
      text: 'What is the primary function of the Federal Reserve?',
      type: 'multiple_choice',
      options: {
        a: 'To collect taxes',
        b: 'To control monetary policy and manage the banking system',
        c: 'To enforce laws',
        d: 'To conduct foreign policy',
      },
      correctAnswer: 'b',
      explanation: 'The Federal Reserve manages monetary policy and oversees the U.S. banking system.',
      subject: 'social_studies',
      difficulty: 'hard',
    },
    {
      id: 48,
      text: 'Which continent has the largest population?',
      type: 'multiple_choice',
      options: {
        a: 'Africa',
        b: 'Europe',
        c: 'Asia',
        d: 'North America',
      },
      correctAnswer: 'c',
      explanation: 'Asia has the largest population of any continent, with over 4.6 billion people.',
      subject: 'social_studies',
      difficulty: 'easy',
    },
    {
      id: 49,
      text: 'What is the primary purpose of the United States Constitution?',
      type: 'multiple_choice',
      options: {
        a: 'To declare independence from Britain',
        b: 'To establish the framework for the U.S. government',
        c: 'To abolish slavery',
        d: 'To grant voting rights to all citizens',
      },
      correctAnswer: 'b',
      explanation: 'The Constitution establishes the structure and powers of the U.S. government.',
      subject: 'social_studies',
      difficulty: 'easy',
    },
    {
      id: 50,
      text: 'Which of the following is an example of a renewable resource?',
      type: 'multiple_choice',
      options: {
        a: 'Coal',
        b: 'Oil',
        c: 'Forests',
        d: 'Natural gas',
      },
      correctAnswer: 'c',
      explanation: 'Forests are renewable resources because they can be replanted and regrow.',
      subject: 'social_studies',
      difficulty: 'easy',
    },
  ],
};
