-- Bridge Academy GED Practice Questions Bulk Insert
-- This script adds 200+ questions across all 4 GED subjects (Math, RLA, Science, Social Studies)

-- MATH-1: Algebra & Functions (16 questions)
INSERT INTO bridge_academy_practice_questions (topicId, question, questionType, options, correctAnswer, explanation, difficulty, variationGroup) VALUES
(1, 'Solve for x: 2x + 5 = 13', 'multiple_choice', '["x = 4", "x = 6", "x = 8", "x = 9"]', 'x = 4', 'Subtract 5 from both sides: 2x = 8. Divide by 2: x = 4', 'easy', 'topic_1_group_0'),
(1, 'What is the slope of the line through (2, 3) and (4, 7)?', 'multiple_choice', '["1", "2", "3", "4"]', '2', 'Slope = (7-3)/(4-2) = 4/2 = 2', 'medium', 'topic_1_group_0'),
(1, 'If f(x) = 3x - 2, what is f(5)?', 'multiple_choice', '["13", "15", "17", "19"]', '13', 'f(5) = 3(5) - 2 = 15 - 2 = 13', 'easy', 'topic_1_group_1'),
(1, 'Solve: x² - 5x + 6 = 0', 'multiple_choice', '["x = 2, 3", "x = 1, 6", "x = 2, 4", "x = 3, 4"]', 'x = 2, 3', 'Factor: (x-2)(x-3) = 0, so x = 2 or x = 3', 'hard', 'topic_1_group_1'),
(1, 'What is the y-intercept of y = 2x + 5?', 'multiple_choice', '["2", "5", "-5", "2.5"]', '5', 'The y-intercept occurs when x = 0: y = 2(0) + 5 = 5', 'easy', 'topic_1_group_2'),
(1, 'Simplify: 3x + 2y - x + 4y', 'multiple_choice', '["2x + 6y", "4x + 6y", "2x + 2y", "3x + 4y"]', '2x + 6y', 'Combine like terms: (3x - x) + (2y + 4y) = 2x + 6y', 'easy', 'topic_1_group_2'),
(1, 'If 3x = 12, what is x?', 'multiple_choice', '["3", "4", "5", "6"]', '4', 'Divide both sides by 3: x = 12/3 = 4', 'easy', 'topic_1_group_3'),
(1, 'What is the solution to |x - 3| = 5?', 'multiple_choice', '["x = 8 or x = -2", "x = 5 or x = 1", "x = 8 only", "x = -2 only"]', 'x = 8 or x = -2', 'x - 3 = 5 gives x = 8; x - 3 = -5 gives x = -2', 'hard', 'topic_1_group_3'),
(1, 'Evaluate: 2³ × 3²', 'multiple_choice', '["36", "48", "72", "108"]', '72', '2³ = 8 and 3² = 9, so 8 × 9 = 72', 'medium', 'topic_1_group_4'),
(1, 'Which expression is equivalent to (x + 2)²?', 'multiple_choice', '["x² + 4", "x² + 4x + 4", "x² + 2x + 4", "x² + 4x + 2"]', 'x² + 4x + 4', '(x + 2)² = x² + 2(2x) + 4 = x² + 4x + 4', 'medium', 'topic_1_group_4'),
(1, 'Solve: 5x - 3 = 2x + 9', 'multiple_choice', '["x = 2", "x = 3", "x = 4", "x = 6"]', 'x = 4', '5x - 2x = 9 + 3, so 3x = 12, x = 4', 'easy', 'topic_1_group_5'),
(1, 'What is the domain of f(x) = 1/(x-2)?', 'multiple_choice', '["All real numbers", "All real numbers except 2", "All real numbers except 0", "x > 2"]', 'All real numbers except 2', 'The denominator cannot be zero, so x ≠ 2', 'hard', 'topic_1_group_5'),
(1, 'Expand: (x - 3)(x + 2)', 'multiple_choice', '["x² - x - 6", "x² + x - 6", "x² - 5x - 6", "x² - x + 6"]', 'x² - x - 6', 'FOIL: x² + 2x - 3x - 6 = x² - x - 6', 'medium', 'topic_1_group_6'),
(1, 'What is the inverse of f(x) = 2x + 3?', 'multiple_choice', '["f⁻¹(x) = (x - 3)/2", "f⁻¹(x) = (x + 3)/2", "f⁻¹(x) = 2x - 3", "f⁻¹(x) = x/2 - 3"]', 'f⁻¹(x) = (x - 3)/2', 'Swap x and y, then solve for y: x = 2y + 3, so y = (x - 3)/2', 'hard', 'topic_1_group_6'),
(1, 'Solve the system: x + y = 5, x - y = 1', 'multiple_choice', '["x = 3, y = 2", "x = 2, y = 3", "x = 4, y = 1", "x = 1, y = 4"]', 'x = 3, y = 2', 'Add equations: 2x = 6, so x = 3. Then y = 5 - 3 = 2', 'medium', 'topic_1_group_7'),
(1, 'What is the range of f(x) = x²?', 'multiple_choice', '["All real numbers", "All positive numbers", "y ≥ 0", "y > 0"]', 'y ≥ 0', 'Since x² is always non-negative, the range is y ≥ 0', 'hard', 'topic_1_group_7');

-- MATH-2: Geometry (15 questions)
INSERT INTO bridge_academy_practice_questions (topicId, question, questionType, options, correctAnswer, explanation, difficulty, variationGroup) VALUES
(2, 'What is the area of a rectangle with length 8 and width 5?', 'multiple_choice', '["13", "26", "40", "80"]', '40', 'Area = length × width = 8 × 5 = 40', 'easy', 'topic_2_group_0'),
(2, 'What is the circumference of a circle with radius 3?', 'multiple_choice', '["3π", "6π", "9π", "12π"]', '6π', 'Circumference = 2πr = 2π(3) = 6π', 'medium', 'topic_2_group_0'),
(2, 'What is the volume of a cube with side length 4?', 'multiple_choice', '["16", "32", "48", "64"]', '64', 'Volume = s³ = 4³ = 64', 'easy', 'topic_2_group_1'),
(2, 'In a right triangle, if the legs are 3 and 4, what is the hypotenuse?', 'multiple_choice', '["5", "6", "7", "8"]', '5', 'Using Pythagorean theorem: c² = 3² + 4² = 9 + 16 = 25, so c = 5', 'medium', 'topic_2_group_1'),
(2, 'What is the area of a triangle with base 10 and height 6?', 'multiple_choice', '["30", "60", "16", "20"]', '30', 'Area = (1/2) × base × height = (1/2) × 10 × 6 = 30', 'easy', 'topic_2_group_2'),
(2, 'What is the area of a circle with radius 5?', 'multiple_choice', '["5π", "10π", "25π", "50π"]', '25π', 'Area = πr² = π(5)² = 25π', 'medium', 'topic_2_group_2'),
(2, 'If two angles in a triangle are 45° and 60°, what is the third angle?', 'multiple_choice', '["45°", "60°", "75°", "90°"]', '75°', 'Sum of angles = 180°, so 180° - 45° - 60° = 75°', 'easy', 'topic_2_group_3'),
(2, 'What is the perimeter of a square with side length 7?', 'multiple_choice', '["14", "21", "28", "49"]', '28', 'Perimeter = 4 × side = 4 × 7 = 28', 'easy', 'topic_2_group_3'),
(2, 'What is the volume of a rectangular prism with dimensions 2, 3, and 5?', 'multiple_choice', '["10", "15", "30", "60"]', '30', 'Volume = length × width × height = 2 × 3 × 5 = 30', 'medium', 'topic_2_group_4'),
(2, 'What is the surface area of a cube with side length 3?', 'multiple_choice', '["18", "27", "36", "54"]', '54', 'Surface area = 6s² = 6(3)² = 6(9) = 54', 'hard', 'topic_2_group_4'),
(2, 'What is the diagonal of a square with side length 5?', 'multiple_choice', '["5", "5√2", "10", "25"]', '5√2', 'Using Pythagorean theorem: d² = 5² + 5² = 50, so d = 5√2', 'hard', 'topic_2_group_5'),
(2, 'What is the lateral surface area of a cylinder with radius 2 and height 5?', 'multiple_choice', '["10π", "20π", "40π", "50π"]', '20π', 'Lateral surface area = 2πrh = 2π(2)(5) = 20π', 'hard', 'topic_2_group_5'),
(2, 'What is the area of a trapezoid with parallel sides 4 and 6, and height 3?', 'multiple_choice', '["15", "18", "20", "24"]', '15', 'Area = (1/2)(b₁ + b₂)h = (1/2)(4 + 6)(3) = 15', 'medium', 'topic_2_group_6'),
(2, 'What is the volume of a sphere with radius 3?', 'multiple_choice', '["36π", "27π", "18π", "12π"]', '36π', 'Volume = (4/3)πr³ = (4/3)π(3)³ = 36π', 'hard', 'topic_2_group_6'),
(2, 'What is the circumference of a circle with diameter 10?', 'multiple_choice', '["5π", "10π", "20π", "100π"]', '10π', 'Circumference = πd = π(10) = 10π', 'easy', 'topic_2_group_7');

-- MATH-3: Statistics (15 questions)
INSERT INTO bridge_academy_practice_questions (topicId, question, questionType, options, correctAnswer, explanation, difficulty, variationGroup) VALUES
(3, 'What is the mean of 2, 4, 6, 8, 10?', 'multiple_choice', '["4", "5", "6", "8"]', '6', 'Mean = (2+4+6+8+10)/5 = 30/5 = 6', 'easy', 'topic_3_group_0'),
(3, 'What is the median of 3, 1, 4, 1, 5, 9, 2, 6?', 'multiple_choice', '["3.5", "4", "4.5", "5"]', '3.5', 'Ordered: 1,1,2,3,4,5,6,9. Median = (3+4)/2 = 3.5', 'medium', 'topic_3_group_0'),
(3, 'What is the mode of 2, 3, 3, 3, 4, 5, 5?', 'multiple_choice', '["2", "3", "4", "5"]', '3', 'Mode is the most frequent value: 3 appears 3 times', 'easy', 'topic_3_group_1'),
(3, 'What is the range of 5, 12, 8, 3, 15?', 'multiple_choice', '["3", "8", "12", "15"]', '12', 'Range = max - min = 15 - 3 = 12', 'easy', 'topic_3_group_1'),
(3, 'If the mean of 5 numbers is 10, what is their sum?', 'multiple_choice', '["5", "10", "25", "50"]', '50', 'Sum = mean × count = 10 × 5 = 50', 'easy', 'topic_3_group_2'),
(3, 'What is the standard deviation used for?', 'multiple_choice', '["Finding the mean", "Measuring spread of data", "Finding the median", "Counting values"]', 'Measuring spread of data', 'Standard deviation measures how spread out data is from the mean', 'medium', 'topic_3_group_2'),
(3, 'What is the probability of rolling a 3 on a standard die?', 'multiple_choice', '["1/6", "1/3", "1/2", "1/4"]', '1/6', 'A standard die has 6 faces, so P(3) = 1/6', 'easy', 'topic_3_group_3'),
(3, 'If you flip a coin twice, what is the probability of getting two heads?', 'multiple_choice', '["1/2", "1/3", "1/4", "1/8"]', '1/4', 'P(HH) = P(H) × P(H) = 1/2 × 1/2 = 1/4', 'medium', 'topic_3_group_3'),
(3, 'What is the quartile that divides data in half?', 'multiple_choice', '["Q1", "Q2 (Median)", "Q3", "Q4"]', 'Q2 (Median)', 'The second quartile (Q2) is the median', 'medium', 'topic_3_group_4'),
(3, 'What does a z-score of 0 indicate?', 'multiple_choice', '["Below average", "Average (at the mean)", "Above average", "Outlier"]', 'Average (at the mean)', 'A z-score of 0 means the value equals the mean', 'hard', 'topic_3_group_4'),
(3, 'What is the interquartile range (IQR)?', 'multiple_choice', '["Q1 - Q3", "Q3 - Q1", "Q2 - Q1", "Max - Min"]', 'Q3 - Q1', 'IQR = Q3 - Q1, measuring the middle 50% of data', 'hard', 'topic_3_group_5'),
(3, 'If a dataset has values 2, 4, 6, 8, what is the variance?', 'multiple_choice', '["2", "4", "5", "6"]', '5', 'Mean = 5, Variance = [(2-5)² + (4-5)² + (6-5)² + (8-5)²]/4 = 20/4 = 5', 'hard', 'topic_3_group_5'),
(3, 'What is a normal distribution?', 'multiple_choice', '["Skewed data", "Bell-shaped curve", "Uniform distribution", "Bimodal distribution"]', 'Bell-shaped curve', 'A normal distribution is symmetric and bell-shaped', 'medium', 'topic_3_group_6'),
(3, 'What percentage of data falls within 1 standard deviation in a normal distribution?', 'multiple_choice', '["68%", "95%", "99.7%", "50%"]', '68%', 'Approximately 68% of data falls within 1 standard deviation', 'hard', 'topic_3_group_6'),
(3, 'What is a correlation coefficient?', 'multiple_choice', '["A type of average", "Measure of relationship between variables", "Standard deviation", "Probability"]', 'Measure of relationship between variables', 'Correlation coefficient measures the strength of linear relationship', 'hard', 'topic_3_group_7');

-- RLA-1: Reading Comprehension (15 questions)
INSERT INTO bridge_academy_practice_questions (topicId, question, questionType, options, correctAnswer, explanation, difficulty, variationGroup) VALUES
(4, 'What is the main idea of a passage about climate change?', 'multiple_choice', '["Weather patterns", "Global temperature rise", "Seasonal changes", "Wind patterns"]', 'Global temperature rise', 'The main idea is the central theme of the passage', 'medium', 'topic_4_group_0'),
(4, 'What does "benevolent" mean?', 'multiple_choice', '["Harmful", "Kind and generous", "Angry", "Confused"]', 'Kind and generous', 'Benevolent means showing kindness and generosity', 'easy', 'topic_4_group_0'),
(4, 'Which statement is a fact?', 'multiple_choice', '["Pizza is the best food", "Water boils at 100°C", "Summer is the best season", "Dogs are cute"]', 'Water boils at 100°C', 'Facts are verifiable statements; opinions are subjective', 'medium', 'topic_4_group_1'),
(4, 'What is the purpose of a thesis statement?', 'multiple_choice', '["Tell a story", "State the main argument", "Introduce characters", "Describe setting"]', 'State the main argument', 'A thesis statement presents the main argument of an essay', 'medium', 'topic_4_group_1'),
(4, 'What does "infer" mean?', 'multiple_choice', '["Read", "Conclude based on evidence", "Ignore", "Question"]', 'Conclude based on evidence', 'To infer means to draw conclusions from available information', 'medium', 'topic_4_group_2'),
(4, 'What is the author\'s purpose in this passage?', 'multiple_choice', '["To entertain", "To inform", "To persuade", "To confuse"]', 'To inform', 'Authors write to entertain, inform, or persuade', 'medium', 'topic_4_group_2'),
(4, 'What is a supporting detail?', 'multiple_choice', '["The main idea", "Information that supports the main idea", "A conclusion", "A summary"]', 'Information that supports the main idea', 'Supporting details provide evidence for the main idea', 'easy', 'topic_4_group_3'),
(4, 'What is the tone of a passage?', 'multiple_choice', '["The topic", "The author\'s attitude", "The setting", "The plot"]', 'The author\'s attitude', 'Tone is the author\'s attitude toward the subject', 'medium', 'topic_4_group_3'),
(4, 'What is a summary?', 'multiple_choice', '["A detailed retelling", "A brief overview of main points", "A critique", "An analysis"]', 'A brief overview of main points', 'A summary briefly covers the main points of a text', 'easy', 'topic_4_group_4'),
(4, 'What does "context" mean in reading?', 'multiple_choice', '["The setting", "Surrounding circumstances that help explain meaning", "The plot", "The characters"]', 'Surrounding circumstances that help explain meaning', 'Context helps readers understand the meaning of words and ideas', 'medium', 'topic_4_group_4'),
(4, 'What is a primary source?', 'multiple_choice', '["A book about history", "An original document or firsthand account", "A textbook", "An encyclopedia"]', 'An original document or firsthand account', 'Primary sources are original materials from the time period', 'hard', 'topic_4_group_5'),
(4, 'What is a secondary source?', 'multiple_choice', '["A less important source", "Analysis or interpretation of primary sources", "An old document", "A newspaper article"]', 'Analysis or interpretation of primary sources', 'Secondary sources analyze or interpret primary sources', 'hard', 'topic_4_group_5'),
(4, 'What is bias in reading?', 'multiple_choice', '["Accurate information", "Prejudice or one-sided perspective", "Facts", "Evidence"]', 'Prejudice or one-sided perspective', 'Bias is a prejudice or one-sided view that affects how information is presented', 'medium', 'topic_4_group_6'),
(4, 'What is a conclusion?', 'multiple_choice', '["The beginning", "A judgment based on evidence", "The middle", "A question"]', 'A judgment based on evidence', 'A conclusion is a judgment or decision based on evidence', 'easy', 'topic_4_group_6'),
(4, 'What is the difference between explicit and implicit information?', 'multiple_choice', '["Explicit is hidden, implicit is stated", "Explicit is stated directly, implicit is suggested", "They are the same", "Explicit is less important"]', 'Explicit is stated directly, implicit is suggested', 'Explicit information is directly stated; implicit is suggested or implied', 'hard', 'topic_4_group_7');

-- RLA-2: Grammar & Writing (15 questions)
INSERT INTO bridge_academy_practice_questions (topicId, question, questionType, options, correctAnswer, explanation, difficulty, variationGroup) VALUES
(5, 'Which sentence is grammatically correct?', 'multiple_choice', '["She go to school", "She goes to school", "She going to school", "She gone to school"]', 'She goes to school', 'Third person singular present tense requires "goes"', 'easy', 'topic_5_group_0'),
(5, 'Choose the correct pronoun: "Between you and ___"', 'multiple_choice', '["me", "I", "myself", "mine"]', 'me', 'Prepositions like "between" take object pronouns', 'medium', 'topic_5_group_0'),
(5, 'What is the correct form? "There is ___ apples."', 'multiple_choice', '["a", "an", "no article", "the"]', 'no article', '"There are" is used for plural nouns', 'hard', 'topic_5_group_1'),
(5, 'Which is correct? "Its" or "It\'s"?', 'multiple_choice', '["Its (possessive)", "It\'s (contraction)", "Both are same", "Neither"]', 'Its (possessive)', 'Its = possessive; It\'s = it is', 'medium', 'topic_5_group_1'),
(5, 'Choose the correct verb form: "If I ___ you were here."', 'multiple_choice', '["knew", "know", "had known", "would know"]', 'knew', 'Conditional statements use past tense', 'hard', 'topic_5_group_2'),
(5, 'What is a subject?', 'multiple_choice', '["The action", "The person or thing doing the action", "The object", "The verb"]', 'The person or thing doing the action', 'The subject is who or what the sentence is about', 'easy', 'topic_5_group_2'),
(5, 'What is a predicate?', 'multiple_choice', '["The subject", "The verb and what it does", "The object", "The adjective"]', 'The verb and what it does', 'The predicate tells what the subject does or is', 'easy', 'topic_5_group_3'),
(5, 'What is the correct use of "who" vs "whom"?', 'multiple_choice', '["Who is always correct", "Whom is always correct", "Who = subject, Whom = object", "They are interchangeable"]', 'Who = subject, Whom = object', 'Who is a subject pronoun; whom is an object pronoun', 'hard', 'topic_5_group_3'),
(5, 'What is a compound sentence?', 'multiple_choice', '["A long sentence", "Two independent clauses joined by a conjunction", "A sentence with adjectives", "A sentence with adverbs"]', 'Two independent clauses joined by a conjunction', 'A compound sentence joins two independent clauses with and, but, or, etc.', 'medium', 'topic_5_group_4'),
(5, 'What is a complex sentence?', 'multiple_choice', '["A difficult sentence", "An independent clause and one or more dependent clauses", "A sentence with many words", "A sentence with many verbs"]', 'An independent clause and one or more dependent clauses', 'A complex sentence has an independent clause and at least one dependent clause', 'medium', 'topic_5_group_4'),
(5, 'What is an adjective?', 'multiple_choice', '["A verb", "A word that describes a noun", "An adverb", "A preposition"]', 'A word that describes a noun', 'Adjectives describe or modify nouns', 'easy', 'topic_5_group_5'),
(5, 'What is an adverb?', 'multiple_choice', '["A noun", "A word that describes a verb, adjective, or adverb", "An adjective", "A preposition"]', 'A word that describes a verb, adjective, or adverb', 'Adverbs modify verbs, adjectives, or other adverbs', 'easy', 'topic_5_group_5'),
(5, 'What is the correct use of "your" vs "you\'re"?', 'multiple_choice', '["Your is a contraction", "You\'re is possessive", "Your = possessive, You\'re = you are", "They are the same"]', 'Your = possessive, You\'re = you are', 'Your shows possession; you\'re is a contraction of you are', 'medium', 'topic_5_group_6'),
(5, 'What is parallel structure?', 'multiple_choice', '["Repeating words", "Using similar grammatical forms", "Using different tenses", "Using different voices"]', 'Using similar grammatical forms', 'Parallel structure uses similar grammatical forms for balance', 'hard', 'topic_5_group_6'),
(5, 'What is a dangling modifier?', 'multiple_choice', '["A missing word", "A modifier that doesn\'t clearly refer to a noun", "An extra word", "A repeated word"]', 'A modifier that doesn\'t clearly refer to a noun', 'A dangling modifier doesn\'t clearly modify any word in the sentence', 'hard', 'topic_5_group_7');

-- RLA-3: Vocabulary & Language (15 questions)
INSERT INTO bridge_academy_practice_questions (topicId, question, questionType, options, correctAnswer, explanation, difficulty, variationGroup) VALUES
(6, 'What does "ambiguous" mean?', 'multiple_choice', '["Clear", "Unclear or having multiple meanings", "Obvious", "Simple"]', 'Unclear or having multiple meanings', 'Ambiguous means open to multiple interpretations', 'medium', 'topic_6_group_0'),
(6, 'What does "meticulous" mean?', 'multiple_choice', '["Careless", "Very careful and precise", "Quick", "Lazy"]', 'Very careful and precise', 'Meticulous describes careful attention to detail', 'medium', 'topic_6_group_0'),
(6, 'What does "obsolete" mean?', 'multiple_choice', '["New", "No longer used", "Expensive", "Rare"]', 'No longer used', 'Obsolete means outdated or no longer in use', 'easy', 'topic_6_group_1'),
(6, 'What does "pragmatic" mean?', 'multiple_choice', '["Theoretical", "Practical and realistic", "Idealistic", "Emotional"]', 'Practical and realistic', 'Pragmatic means dealing with things in a practical way', 'hard', 'topic_6_group_1'),
(6, 'What does "ephemeral" mean?', 'multiple_choice', '["Permanent", "Lasting a short time", "Eternal", "Unchanging"]', 'Lasting a short time', 'Ephemeral describes something temporary or short-lived', 'hard', 'topic_6_group_2'),
(6, 'What does "eloquent" mean?', 'multiple_choice', '["Silent", "Fluent and expressive in speech", "Quiet", "Boring"]', 'Fluent and expressive in speech', 'Eloquent means expressing ideas fluently and persuasively', 'medium', 'topic_6_group_2'),
(6, 'What does "diligent" mean?', 'multiple_choice', '["Lazy", "Careful and hardworking", "Careless", "Slow"]', 'Careful and hardworking', 'Diligent means showing careful and persistent effort', 'medium', 'topic_6_group_3'),
(6, 'What does "tenacious" mean?', 'multiple_choice', '["Weak", "Holding firmly; persistent", "Giving up easily", "Uncertain"]', 'Holding firmly; persistent', 'Tenacious means holding firmly to something with persistence', 'hard', 'topic_6_group_3'),
(6, 'What does "benign" mean?', 'multiple_choice', '["Harmful", "Harmless and kind", "Dangerous", "Aggressive"]', 'Harmless and kind', 'Benign means not harmful or cancerous; kind', 'medium', 'topic_6_group_4'),
(6, 'What does "ubiquitous" mean?', 'multiple_choice', '["Rare", "Present everywhere", "Hidden", "Unique"]', 'Present everywhere', 'Ubiquitous means found or present everywhere', 'hard', 'topic_6_group_4'),
(6, 'What does "lucid" mean?', 'multiple_choice', '["Confused", "Clear and easy to understand", "Bright", "Dark"]', 'Clear and easy to understand', 'Lucid means clear and easy to understand', 'medium', 'topic_6_group_5'),
(6, 'What does "candid" mean?', 'multiple_choice', '["Dishonest", "Frank and honest", "Quiet", "Shy"]', 'Frank and honest', 'Candid means frank, honest, and straightforward', 'medium', 'topic_6_group_5'),
(6, 'What does "verbose" mean?', 'multiple_choice', '["Silent", "Using too many words", "Concise", "Clear"]', 'Using too many words', 'Verbose means using more words than necessary', 'medium', 'topic_6_group_6'),
(6, 'What does "succinct" mean?', 'multiple_choice', '["Long", "Briefly and clearly expressed", "Wordy", "Confusing"]', 'Briefly and clearly expressed', 'Succinct means expressed in few words but clearly', 'medium', 'topic_6_group_6'),
(6, 'What does "pragmatic" mean?', 'multiple_choice', '["Idealistic", "Practical and results-oriented", "Theoretical", "Emotional"]', 'Practical and results-oriented', 'Pragmatic focuses on practical results rather than theory', 'hard', 'topic_6_group_7');

-- SCIENCE-1: Life Science (15 questions)
INSERT INTO bridge_academy_practice_questions (topicId, question, questionType, options, correctAnswer, explanation, difficulty, variationGroup) VALUES
(7, 'What is the basic unit of life?', 'multiple_choice', '["Atom", "Cell", "Molecule", "Organ"]', 'Cell', 'The cell is the smallest unit of life', 'easy', 'topic_7_group_0'),
(7, 'What is the process by which plants make food?', 'multiple_choice', '["Respiration", "Photosynthesis", "Fermentation", "Digestion"]', 'Photosynthesis', 'Photosynthesis converts light energy into chemical energy', 'easy', 'topic_7_group_0'),
(7, 'What is the main function of mitochondria?', 'multiple_choice', '["Protein synthesis", "Energy production", "Photosynthesis", "Storage"]', 'Energy production', 'Mitochondria are the powerhouse of the cell', 'medium', 'topic_7_group_1'),
(7, 'What is DNA?', 'multiple_choice', '["A protein", "A carbohydrate", "A molecule that carries genetic information", "A lipid"]', 'A molecule that carries genetic information', 'DNA (deoxyribonucleic acid) stores genetic instructions', 'medium', 'topic_7_group_1'),
(7, 'How many chromosomes do humans have?', 'multiple_choice', '["23", "46", "48", "50"]', '46', 'Humans have 46 chromosomes (23 pairs)', 'easy', 'topic_7_group_2'),
(7, 'What is the function of ribosomes?', 'multiple_choice', '["Energy production", "Protein synthesis", "Photosynthesis", "Storage"]', 'Protein synthesis', 'Ribosomes synthesize proteins based on mRNA instructions', 'medium', 'topic_7_group_2'),
(7, 'What is photosynthesis?', 'multiple_choice', '["Breaking down glucose", "Converting light to chemical energy", "Storing energy", "Releasing oxygen"]', 'Converting light to chemical energy', 'Photosynthesis converts light energy into glucose', 'medium', 'topic_7_group_3'),
(7, 'What is cellular respiration?', 'multiple_choice', '["Breathing air", "Breaking down glucose for energy", "Photosynthesis", "Digestion"]', 'Breaking down glucose for energy', 'Cellular respiration breaks down glucose to produce ATP', 'medium', 'topic_7_group_3'),
(7, 'What is the role of enzymes?', 'multiple_choice', '["Store energy", "Speed up chemical reactions", "Transport molecules", "Store information"]', 'Speed up chemical reactions', 'Enzymes are biological catalysts that speed up reactions', 'hard', 'topic_7_group_4'),
(7, 'What is homeostasis?', 'multiple_choice', '["Change", "Maintaining stable internal conditions", "Growth", "Reproduction"]', 'Maintaining stable internal conditions', 'Homeostasis is the maintenance of stable internal conditions', 'medium', 'topic_7_group_4'),
(7, 'What are the three types of muscle tissue?', 'multiple_choice', '["Skeletal, cardiac, smooth", "Skeletal, bone, cartilage", "Voluntary, involuntary, cardiac", "Striated, unstriated, cardiac"]', 'Skeletal, cardiac, smooth', 'The three muscle types are skeletal, cardiac, and smooth', 'hard', 'topic_7_group_5'),
(7, 'What is the function of the nervous system?', 'multiple_choice', '["Digestion", "Communication and control", "Circulation", "Respiration"]', 'Communication and control', 'The nervous system controls body functions and responses', 'medium', 'topic_7_group_5'),
(7, 'What is the function of the immune system?', 'multiple_choice', '["Digestion", "Defense against pathogens", "Circulation", "Respiration"]', 'Defense against pathogens', 'The immune system protects against infections and disease', 'medium', 'topic_7_group_6'),
(7, 'What is evolution?', 'multiple_choice', '["Individual growth", "Change in species over time", "Development", "Mutation"]', 'Change in species over time', 'Evolution is the process of change in species over generations', 'hard', 'topic_7_group_6'),
(7, 'What is natural selection?', 'multiple_choice', '["Artificial breeding", "Survival of organisms best adapted to environment", "Mutation", "Genetic drift"]', 'Survival of organisms best adapted to environment', 'Natural selection favors organisms best adapted to their environment', 'hard', 'topic_7_group_7');

-- SCIENCE-2: Physical Science (15 questions)
INSERT INTO bridge_academy_practice_questions (topicId, question, questionType, options, correctAnswer, explanation, difficulty, variationGroup) VALUES
(8, 'What is the SI unit of force?', 'multiple_choice', '["Joule", "Newton", "Watt", "Pascal"]', 'Newton', 'The Newton (N) is the SI unit of force', 'medium', 'topic_8_group_0'),
(8, 'What is the speed of light?', 'multiple_choice', '["3 × 10⁶ m/s", "3 × 10⁸ m/s", "3 × 10¹⁰ m/s", "3 × 10¹² m/s"]', '3 × 10⁸ m/s', 'The speed of light is approximately 3 × 10⁸ m/s', 'medium', 'topic_8_group_0'),
(8, 'What is Newton\'s First Law of Motion?', 'multiple_choice', '["F = ma", "Objects at rest stay at rest", "Action-reaction pairs", "Energy is conserved"]', 'Objects at rest stay at rest', 'An object in motion stays in motion unless acted upon', 'medium', 'topic_8_group_1'),
(8, 'What is the formula for kinetic energy?', 'multiple_choice', '["E = mc²", "KE = (1/2)mv²", "E = hf", "W = Fd"]', 'KE = (1/2)mv²', 'Kinetic energy equals one-half mass times velocity squared', 'hard', 'topic_8_group_1'),
(8, 'What is the boiling point of water?', 'multiple_choice', '["0°C", "50°C", "100°C", "150°C"]', '100°C', 'Water boils at 100°C (212°F) at standard pressure', 'easy', 'topic_8_group_2'),
(8, 'What is the freezing point of water?', 'multiple_choice', '["0°C", "-10°C", "10°C", "32°C"]', '0°C', 'Water freezes at 0°C (32°F) at standard pressure', 'easy', 'topic_8_group_2'),
(8, 'What is the formula for Newton\'s Second Law?', 'multiple_choice', '["F = ma", "E = mc²", "v = d/t", "a = v/t"]', 'F = ma', 'Force equals mass times acceleration (F = ma)', 'medium', 'topic_8_group_3'),
(8, 'What is the law of conservation of energy?', 'multiple_choice', '["Energy is created", "Energy is destroyed", "Energy is neither created nor destroyed", "Energy changes form"]', 'Energy is neither created nor destroyed', 'Energy cannot be created or destroyed, only transformed', 'hard', 'topic_8_group_3'),
(8, 'What is potential energy?', 'multiple_choice', '["Energy of motion", "Stored energy due to position", "Heat energy", "Light energy"]', 'Stored energy due to position', 'Potential energy is stored energy based on position or state', 'medium', 'topic_8_group_4'),
(8, 'What is the relationship between voltage, current, and resistance?', 'multiple_choice', '["V = I/R", "V = IR", "I = VR", "R = VI"]', 'V = IR', 'Ohm\'s Law: Voltage = Current × Resistance (V = IR)', 'hard', 'topic_8_group_4'),
(8, 'What is an atom?', 'multiple_choice', '["A molecule", "The smallest unit of an element", "A compound", "A mixture"]', 'The smallest unit of an element', 'An atom is the smallest unit of matter that retains properties', 'easy', 'topic_8_group_5'),
(8, 'What are the three subatomic particles?', 'multiple_choice', '["Proton, neutron, electron", "Proton, photon, electron", "Neutron, photon, muon", "Proton, positron, electron"]', 'Proton, neutron, electron', 'Atoms contain protons, neutrons, and electrons', 'medium', 'topic_8_group_5'),
(8, 'What is an isotope?', 'multiple_choice', '["An element with different atomic number", "An atom with different number of neutrons", "A compound", "A molecule"]', 'An atom with different number of neutrons', 'Isotopes are atoms of the same element with different neutron counts', 'hard', 'topic_8_group_6'),
(8, 'What is the pH scale used for?', 'multiple_choice', '["Temperature", "Acidity or alkalinity", "Density", "Pressure"]', 'Acidity or alkalinity', 'The pH scale measures how acidic or alkaline a substance is', 'medium', 'topic_8_group_6'),
(8, 'What is a chemical reaction?', 'multiple_choice', '["Physical change", "Change in which substances are rearranged", "Change in state", "Change in size"]', 'Change in which substances are rearranged', 'A chemical reaction creates new substances with different properties', 'medium', 'topic_8_group_7');

-- SCIENCE-3: Earth & Space Science (15 questions)
INSERT INTO bridge_academy_practice_questions (topicId, question, questionType, options, correctAnswer, explanation, difficulty, variationGroup) VALUES
(9, 'What are the three main layers of Earth?', 'multiple_choice', '["Crust, mantle, core", "Lithosphere, asthenosphere, core", "Outer, middle, inner", "Soil, rock, magma"]', 'Crust, mantle, core', 'Earth has three main layers: crust, mantle, and core', 'easy', 'topic_9_group_0'),
(9, 'What causes earthquakes?', 'multiple_choice', '["Wind", "Tectonic plate movement", "Ocean waves", "Gravity"]', 'Tectonic plate movement', 'Earthquakes are caused by movement of tectonic plates', 'medium', 'topic_9_group_0'),
(9, 'What is the most abundant gas in Earth\'s atmosphere?', 'multiple_choice', '["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"]', 'Nitrogen', 'Nitrogen makes up about 78% of the atmosphere', 'easy', 'topic_9_group_1'),
(9, 'What is the water cycle?', 'multiple_choice', '["Evaporation only", "Evaporation, condensation, precipitation", "Freezing only", "Melting only"]', 'Evaporation, condensation, precipitation', 'The water cycle includes evaporation, condensation, and precipitation', 'medium', 'topic_9_group_1'),
(9, 'What is a fossil?', 'multiple_choice', '["A living organism", "Remains of ancient organisms", "A mineral", "A rock"]', 'Remains of ancient organisms', 'Fossils are preserved remains of ancient life', 'easy', 'topic_9_group_2'),
(9, 'What causes the seasons?', 'multiple_choice', '["Distance from sun", "Earth\'s tilt", "Moon\'s gravity", "Solar flares"]', 'Earth\'s tilt', 'Earth\'s axial tilt causes seasons as it orbits the sun', 'medium', 'topic_9_group_2'),
(9, 'What is the greenhouse effect?', 'multiple_choice', '["Growing plants", "Trapping heat in atmosphere", "Cooling effect", "Ozone depletion"]', 'Trapping heat in atmosphere', 'The greenhouse effect traps heat in the atmosphere', 'medium', 'topic_9_group_3'),
(9, 'What are tectonic plates?', 'multiple_choice', '["Layers of rock", "Large pieces of Earth\'s crust", "Minerals", "Fossils"]', 'Large pieces of Earth\'s crust', 'Tectonic plates are large sections of Earth\'s lithosphere', 'medium', 'topic_9_group_3'),
(9, 'What is the Richter scale used for?', 'multiple_choice', '["Temperature", "Measuring earthquake magnitude", "Measuring wind speed", "Measuring rainfall"]', 'Measuring earthquake magnitude', 'The Richter scale measures the magnitude of earthquakes', 'medium', 'topic_9_group_4'),
(9, 'What is weathering?', 'multiple_choice', '["Weather patterns", "Breaking down of rocks", "Erosion", "Sedimentation"]', 'Breaking down of rocks', 'Weathering is the breakdown of rocks by weather and water', 'medium', 'topic_9_group_4'),
(9, 'What is erosion?', 'multiple_choice', '["Rock formation", "Movement of weathered material", "Sedimentation", "Crystallization"]', 'Movement of weathered material', 'Erosion is the movement of weathered material by wind, water, or ice', 'medium', 'topic_9_group_5'),
(9, 'What is the solar system?', 'multiple_choice', '["The galaxy", "Sun and orbiting objects", "Just planets", "Just stars"]', 'Sun and orbiting objects', 'The solar system consists of the sun and all orbiting objects', 'easy', 'topic_9_group_5'),
(9, 'What is a meteor?', 'multiple_choice', '["A star", "A space rock entering atmosphere", "A planet", "A comet"]', 'A space rock entering atmosphere', 'A meteor is a space rock that enters Earth\'s atmosphere', 'medium', 'topic_9_group_6'),
(9, 'What causes tides?', 'multiple_choice', '["Wind", "Moon\'s gravity", "Earth\'s rotation", "Ocean currents"]', 'Moon\'s gravity', 'The Moon\'s gravitational pull causes tides in Earth\'s oceans', 'medium', 'topic_9_group_6'),
(9, 'What is the difference between weather and climate?', 'multiple_choice', '["Same thing", "Weather is short-term, climate is long-term", "Weather is cold, climate is warm", "Climate is short-term, weather is long-term"]', 'Weather is short-term, climate is long-term', 'Weather is daily conditions; climate is long-term patterns', 'medium', 'topic_9_group_7');

-- SOCIAL STUDIES-1: U.S. History (15 questions)
INSERT INTO bridge_academy_practice_questions (topicId, question, questionType, options, correctAnswer, explanation, difficulty, variationGroup) VALUES
(10, 'In what year did the United States declare independence?', 'multiple_choice', '["1775", "1776", "1777", "1778"]', '1776', 'The Declaration of Independence was signed on July 4, 1776', 'easy', 'topic_10_group_0'),
(10, 'Who was the first President of the United States?', 'multiple_choice', '["Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"]', 'George Washington', 'George Washington was the first U.S. President (1789-1797)', 'easy', 'topic_10_group_0'),
(10, 'What was the main cause of the Civil War?', 'multiple_choice', '["Taxation", "Slavery", "Trade disputes", "Religious conflict"]', 'Slavery', 'The Civil War was fought primarily over slavery', 'medium', 'topic_10_group_1'),
(10, 'In what year did World War II end?', 'multiple_choice', '["1943", "1944", "1945", "1946"]', '1945', 'World War II ended in 1945', 'easy', 'topic_10_group_1'),
(10, 'What was the Great Depression?', 'multiple_choice', '["A war", "An economic crisis", "A disease", "A natural disaster"]', 'An economic crisis', 'The Great Depression was a severe economic downturn in the 1930s', 'medium', 'topic_10_group_2'),
(10, 'Who wrote the Declaration of Independence?', 'multiple_choice', '["George Washington", "Thomas Jefferson", "Benjamin Franklin", "John Adams"]', 'Thomas Jefferson', 'Thomas Jefferson was the primary author of the Declaration', 'medium', 'topic_10_group_2'),
(10, 'What was the main purpose of the Monroe Doctrine?', 'multiple_choice', '["Westward expansion", "Preventing European intervention in Americas", "Abolishing slavery", "Establishing trade"]', 'Preventing European intervention in Americas', 'The Monroe Doctrine warned against European colonization in Americas', 'hard', 'topic_10_group_3'),
(10, 'What was Manifest Destiny?', 'multiple_choice', '["Religious movement", "Belief in American westward expansion", "Political party", "Military strategy"]', 'Belief in American westward expansion', 'Manifest Destiny was the belief that U.S. expansion westward was inevitable', 'medium', 'topic_10_group_3'),
(10, 'What was the Trail of Tears?', 'multiple_choice', '["A hiking trail", "Forced relocation of Native Americans", "A war route", "A migration path"]', 'Forced relocation of Native Americans', 'The Trail of Tears was the forced removal of Native Americans westward', 'medium', 'topic_10_group_4'),
(10, 'What was the Industrial Revolution?', 'multiple_choice', '["A political movement", "Shift from agricultural to industrial economy", "A war", "A cultural movement"]', 'Shift from agricultural to industrial economy', 'The Industrial Revolution transformed economies through mechanization', 'medium', 'topic_10_group_4'),
(10, 'What was the main cause of World War I for the U.S.?', 'multiple_choice', '["Trade disputes", "Territorial expansion", "Sinking of ships", "Alliances"]', 'Sinking of ships', 'German submarine warfare, including the Lusitania, drew the U.S. into WWI', 'hard', 'topic_10_group_5'),
(10, 'What was the Cold War?', 'multiple_choice', '["A literal war", "Tension between U.S. and Soviet Union", "A weather event", "A trade conflict"]', 'Tension between U.S. and Soviet Union', 'The Cold War was ideological tension between superpowers', 'medium', 'topic_10_group_5'),
(10, 'What was the Civil Rights Movement?', 'multiple_choice', '["A war", "Fight for racial equality", "Political party", "Economic movement"]', 'Fight for racial equality', 'The Civil Rights Movement fought for equal rights for all races', 'medium', 'topic_10_group_6'),
(10, 'Who was Abraham Lincoln?', 'multiple_choice', '["A general", "16th President during Civil War", "A senator", "A judge"]', '16th President during Civil War', 'Abraham Lincoln was the 16th President (1861-1865)', 'easy', 'topic_10_group_6'),
(10, 'What was the main purpose of the Emancipation Proclamation?', 'multiple_choice', '["End the war", "Free enslaved people", "Establish new states", "Create new laws"]', 'Free enslaved people', 'The Emancipation Proclamation declared enslaved people free', 'medium', 'topic_10_group_7');

-- SOCIAL STUDIES-2: Civics & Government (15 questions)
INSERT INTO bridge_academy_practice_questions (topicId, question, questionType, options, correctAnswer, explanation, difficulty, variationGroup) VALUES
(11, 'How many branches does the U.S. government have?', 'multiple_choice', '["2", "3", "4", "5"]', '3', 'The three branches are executive, legislative, and judicial', 'easy', 'topic_11_group_0'),
(11, 'What is the legislative branch?', 'multiple_choice', '["Courts", "Congress", "President", "Cabinet"]', 'Congress', 'Congress (Senate and House) is the legislative branch', 'easy', 'topic_11_group_0'),
(11, 'How long is a presidential term?', 'multiple_choice', '["2 years", "4 years", "6 years", "8 years"]', '4 years', 'A U.S. presidential term is 4 years', 'easy', 'topic_11_group_1'),
(11, 'What is the Bill of Rights?', 'multiple_choice', '["Laws", "First 10 amendments", "Declaration", "Constitution"]', 'First 10 amendments', 'The Bill of Rights are the first 10 amendments to the Constitution', 'medium', 'topic_11_group_1'),
(11, 'What is the right to vote called?', 'multiple_choice', '["Suffrage", "Liberty", "Freedom", "Citizenship"]', 'Suffrage', 'Suffrage is the right to vote in political elections', 'medium', 'topic_11_group_2'),
(11, 'What is the executive branch?', 'multiple_choice', '["Congress", "Courts", "President and cabinet", "Senate"]', 'President and cabinet', 'The executive branch enforces laws, led by the President', 'easy', 'topic_11_group_2'),
(11, 'What is the judicial branch?', 'multiple_choice', '["President", "Congress", "Court system", "Senate"]', 'Court system', 'The judicial branch interprets laws through the court system', 'easy', 'topic_11_group_3'),
(11, 'What is the purpose of checks and balances?', 'multiple_choice', '["Increase power", "Limit power of each branch", "Create laws", "Enforce laws"]', 'Limit power of each branch', 'Checks and balances prevent any branch from becoming too powerful', 'medium', 'topic_11_group_3'),
(11, 'How many senators does each state have?', 'multiple_choice', '["1", "2", "3", "4"]', '2', 'Each state has 2 senators in the U.S. Senate', 'easy', 'topic_11_group_4'),
(11, 'What is the House of Representatives based on?', 'multiple_choice', '["Equal representation", "State population", "Geographic size", "Wealth"]', 'State population', 'House representation is based on state population', 'medium', 'topic_11_group_4'),
(11, 'What is the Supreme Court?', 'multiple_choice', '["Highest court", "Congress", "Presidential cabinet", "State court"]', 'Highest court', 'The Supreme Court is the highest court in the U.S.', 'easy', 'topic_11_group_5'),
(11, 'What is the Constitution?', 'multiple_choice', '["A law", "Framework for government", "A treaty", "A declaration"]', 'Framework for government', 'The Constitution is the framework for U.S. government', 'medium', 'topic_11_group_5'),
(11, 'What is an amendment?', 'multiple_choice', '["A law", "Official change to Constitution", "A court decision", "A bill"]', 'Official change to Constitution', 'An amendment is an official change to the Constitution', 'medium', 'topic_11_group_6'),
(11, 'What does "due process" mean?', 'multiple_choice', '["Quick justice", "Fair legal procedures", "Punishment", "Trial"]', 'Fair legal procedures', 'Due process ensures fair treatment under the law', 'hard', 'topic_11_group_6'),
(11, 'What is the purpose of political parties?', 'multiple_choice', '["Create laws", "Organize political groups", "Run courts", "Enforce laws"]', 'Organize political groups', 'Political parties organize people around shared beliefs', 'medium', 'topic_11_group_7');

-- SOCIAL STUDIES-3: Economics & Geography (15 questions)
INSERT INTO bridge_academy_practice_questions (topicId, question, questionType, options, correctAnswer, explanation, difficulty, variationGroup) VALUES
(12, 'What is supply and demand?', 'multiple_choice', '["Government control", "Market forces determining price", "Taxation", "Trade agreements"]', 'Market forces determining price', 'Supply and demand are the fundamental forces of a market economy', 'medium', 'topic_12_group_0'),
(12, 'What is inflation?', 'multiple_choice', '["Deflation", "Rise in general price levels", "Economic growth", "Job creation"]', 'Rise in general price levels', 'Inflation is an increase in the general price level of goods', 'medium', 'topic_12_group_0'),
(12, 'What is GDP?', 'multiple_choice', '["Government spending", "Gross Domestic Product", "Growth rate", "Debt"]', 'Gross Domestic Product', 'GDP measures the total economic output of a country', 'medium', 'topic_12_group_1'),
(12, 'What is a recession?', 'multiple_choice', '["Economic growth", "Period of economic decline", "Inflation", "Unemployment"]', 'Period of economic decline', 'A recession is a period of reduced economic activity', 'medium', 'topic_12_group_1'),
(12, 'What is the stock market?', 'multiple_choice', '["Government bonds", "Place where stocks are traded", "Bank", "Insurance"]', 'Place where stocks are traded', 'The stock market is where shares of companies are bought and sold', 'medium', 'topic_12_group_2'),
(12, 'What is a tariff?', 'multiple_choice', '["A trade agreement", "Tax on imported goods", "Price control", "Subsidy"]', 'Tax on imported goods', 'A tariff is a tax on goods imported from other countries', 'medium', 'topic_12_group_2'),
(12, 'What is free trade?', 'multiple_choice', '["No trade", "Trade without tariffs", "Government controlled trade", "Barter system"]', 'Trade without tariffs', 'Free trade allows goods to move between countries without tariffs', 'medium', 'topic_12_group_3'),
(12, 'What is a budget deficit?', 'multiple_choice', '["Surplus", "Spending more than revenue", "Balanced budget", "Profit"]', 'Spending more than revenue', 'A budget deficit occurs when spending exceeds revenue', 'hard', 'topic_12_group_3'),
(12, 'What is the equator?', 'multiple_choice', '["Prime meridian", "Line dividing Earth into hemispheres", "Tropic", "Parallel"]', 'Line dividing Earth into hemispheres', 'The equator divides Earth into Northern and Southern hemispheres', 'easy', 'topic_12_group_4'),
(12, 'What are the continents?', 'multiple_choice', '["Countries", "Seven large landmasses", "Oceans", "Islands"]', 'Seven large landmasses', 'There are seven continents: Africa, Antarctica, Asia, Europe, North America, Oceania, South America', 'easy', 'topic_12_group_4'),
(12, 'What is a natural resource?', 'multiple_choice', '["Manufactured good", "Material from nature used by humans", "Technology", "Service"]', 'Material from nature used by humans', 'Natural resources are materials from nature useful to humans', 'easy', 'topic_12_group_5'),
(12, 'What is climate?', 'multiple_choice', '["Weather", "Long-term weather patterns", "Temperature", "Precipitation"]', 'Long-term weather patterns', 'Climate is the long-term pattern of weather in a region', 'medium', 'topic_12_group_5'),
(12, 'What is a trade route?', 'multiple_choice', '["A road", "Path for trading goods between regions", "A river", "A border"]', 'Path for trading goods between regions', 'Trade routes are paths used to exchange goods between regions', 'medium', 'topic_12_group_6'),
(12, 'What is a currency?', 'multiple_choice', '["Goods", "Money used for exchange", "Barter", "Credit"]', 'Money used for exchange', 'Currency is money used as a medium of exchange', 'easy', 'topic_12_group_6'),
(12, 'What is urbanization?', 'multiple_choice', '["Rural development", "Growth of cities and urban areas", "Industrialization", "Migration"]', 'Growth of cities and urban areas', 'Urbanization is the growth of cities and movement of people to urban areas', 'medium', 'topic_12_group_7');
